spring:
  application:
    name: test-22
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate: 
      ddl-auto: none
  datasource:
    platform: PGSQL
    continue-on-error: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
server:
    contextPath: /test/
    port: 9090
    session:
      timeout: 7200
      timeoutCookieName: session-timeout
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.mybatis